services:
  vnlpkit:
    env_file: .env
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: localhost
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/root
    working_dir: /root
    command: sh run.sh
    restart: always
